[package]
name = "encode_to_curve"
type = "lib"
authors = ["TACEO <hello@taceo.io>"]

[dependencies]
poseidon2 = { tag = "v0.5.0-beta.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
babyjubjub = { path = "../babyjubjub" }
