[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "./script/script-data/pubkey-list.hex"}, { access = "read", path = "./script/script-data/rp-public-key.hex"}]