services:
  postgres:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"            
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
