[package]
name = "oprf-dev-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true

[dependencies]
alloy = { workspace = true, features = ["full", "rpc", "rpc-client-ws", "node-bindings"] }
ark-babyjubjub = { workspace = true }
ark-ff.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
humantime = { workspace = true }
nodes-telemetry.workspace = true
oprf-client = { workspace = true }
oprf-service = { workspace = true }
oprf-test = { workspace = true }
oprf-types = { workspace = true }
parking_lot = { workspace = true }
rand.workspace = true
rand_chacha.workspace = true
reqwest = { workspace = true }
secrecy.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "signal", "sync", "time", "tokio-macros"] }
tracing.workspace = true
