name: Build and Push (oprf-service)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - sg/ghcr
    tags:
      - 'oprf-service-v*'

jobs:

  # test_arm:
  #   runs-on: ubuntu-24.04-arml
  #   steps:
  #     - name: Test
  #       run: |
  #         lscpu

    
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: oprf-service
      dockerfile: build/Dockerfile.test

        

