name: Build and Push (key-gen)

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'key-gen-v*'

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: key-gen
      dockerfile: build/Dockerfile.key-gen

