name: Build and Push (smart-contract-mock)

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'smart-contract-mock-v*'

jobs:
  workflow:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: smart-contract-mock
      dockerfile: build/Dockerfile.smart-contract-mock

