name: Rust Tests

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL
  RUSTFLAGS: "-C link-arg=-fuse-ld=lld"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: sudo apt-get install lld protobuf-compiler
      # - uses: Swatinem/rust-cache@v2
      - name: Unit & Integration Tests
        run: cargo test --workspace --profile ci-dev --all-features
